// <auto-generated />
namespace TicItNow.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Init_Units : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Init_Units));
        
        string IMigrationMetadata.Id
        {
            get { return "201407280616493_Init_Units"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
