// <auto-generated />
namespace TicItNow.Web.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Customers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Customers));
        
        string IMigrationMetadata.Id
        {
            get { return "201408011301488_Customers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
